[package]
name = "lc1"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
insta = { version = "1.43.1", features = ["yaml"] }
serde = { version = "1.0.219", features = ["derive"] }
